version: '3.7'
services:
  dih-services:
    image: dih-base-cronies
    container_name: dih-cronies
    build:
        context: .
        dockerfile: dih.dockerfile
    env_file:
      - .env
    volumes: 
      - ~/.dih.configs:/etc/cronies/config/
    entrypoint: start cronies runner
    networks:
      - dih-network

networks:
  dih-network:
    name: dih-network
    external: true