#!/usr/bin/env python
# apt-get install libbz2-dev ssh-client postgresql-client
# pip install --upgrade pandas openpyxl SQLAlchemy psycopg2-binary google-api-python-client google-auth-httplib2 google-auth-oauthlib oauth2client
# cron_time 0 03 * * 5

import sys

sys.path += ["../../libs", "../src"]
from main import main
import utils as fn


if __name__ == "__main__":
    month = sys.argv[1] if len(sys.argv) > 1 else fn.get_month(-1)
    data = main(
        month = month,
        task_name = "dev-jna-dhis",
        config_file = "/etc/cronies/config/dev.jna.json",
    )
    print(data)
