#!/usr/bin/env python
# apt-get install libbz2-dev ssh-client postgresql-client
# pip install --upgrade pandas openpyxl SQLAlchemy psycopg2-binary google-api-python-client google-auth-httplib2 google-auth-oauthlib oauth2client
# cron_time 03 03 10 * *

# import cProfile
import sys,argparse
sys.path.extend(["../../libs",'../src'])

import main 
import utils as fn

def run():
    if __name__ == "__main__":
        parser = argparse.ArgumentParser(description='Script for pushing data from data warehouse to dhis2')
        parser.add_argument('-m', '--month', type=str, help='Date in format YYYY-MM')
        parser.add_argument('-n', '--only-new', action='store_true', help='Flag for new elements only')
        args = vars(parser.parse_args())  # Convert args to dictionary

        data=main.start(
            config_file="/home/e/.siri/local.jna.json",
            month=fn.parse_month(args['month']) if args.get('month') else fn.get_month(-1),
            task_name="dhis-jna",
            only_new_elements=args.get('only_new')
        )

run()
